### PR TITLE
Add cancellation field to staff hours.

### PR DESCRIPTION
**Pull request by redplanks**
I didn't think of what happens if one person has multiple staff hours, so I think just adding this field is simpler all around.

### CODE REVIEW

**Comment by redplanks** [comment]
Do you mean default cancelled or default not cancelled? I can definitely make the field optional, and have `ocflib` fill in the default if it's not included. I'd have to add another example entry, and it might be a little more confusing. Definitely more scannable though.

**Comment by dkess** [comment]
I'd say ocflib should fill in a default value of false.

**Comment by jvperrin** [comment]
Ah, yeah I meant a default of `false` (as in "not cancelled"), since that should be the common case. I think the double negative just confused me

**Comment by cg505** [comment]
I still think it would be nice if you could cancel without having to make a PR, but I think this is acceptable

**Comment by ethanhs** [comment]
I think our SLO for reviewing/merging PRs is pretty low, so I'm not super worried about requiring making a PR. Though this does make me think we should describe this process at staff meeting at some point.

**Comment by redplanks** [comment]
As long as the CI passes, people should just be able to merge unilaterally

**Comment by ethanhs** [comment]
Also I changed my mind and I agree that people should be able to just make PRs and merge them if they are green.

**Pull request merged**
