### PR TITLE
Add Jenkinsfile

### PR DESCRIPTION
**Pull request by dkess**
A basic Jenkinsfile that runs tests. Probably should have included this in the original commit.

This is actually the exact same Jenkinsfile from the utils repo since we're doing basically the same thing.

### CODE REVIEW

**Comment by jvperrin** [comment]
Isn't this where you want to put the branch promotion stuff when the tests pass, or is that going somewhere else?

**Comment by dkess** [comment]
Gonna try kpengboy's suggestion first and see if GitHub can do this protection for us. If that doesn't work then I'll go ahead with branch promotion.

**Comment by jvperrin** [comment]
That's just for merging PRs though, if someone pushes directly to master or edits the files on GitHub then it wouldn't protect from it, unless you're thinking of preventing those somehow too?

**Comment by dkess** [comment]
I believe GitHub can protect from that too? Otherwise there's no point in trying the other plans, as those would also require that we prevent people from using the web interface to commit directly to the repo.

**Comment by jvperrin** [comment]
I'd say we do want some kind of workaround to push emergency fixes though, like to be able to bypass the tests if needed, say if Jenkins is broken or something like that. And would people really switch to the stable branch if it's not the default and edit that through the web interface? Anyway, I guess see if GitHub protects against those kinds of changes, but I'm confused what the plan is here, since I thought one of the original goals was to still be able to edit through the web interface if wanted and then some validation would be done. Would they have to edit on a separate branch and make a PR, or?

I still think that producing a package out of this would make more sense and be more in line with the other repos we have (utils is probably going to do this soon, if https://github.com/ocf/utils/pull/83 is merged anyway) than having a separate stable branch, but either should technically work in the end.

**Comment by dkess** [comment]
Deploy step has been added. This is basically the same as [dns's deploy step](https://github.com/ocf/dns/blob/master/Jenkinsfile).

**Pull request merged**
