### PR TITLE
rt#8837

### PR DESCRIPTION
**Pull request by nikhiljha**
https://ocf.io/rt/8837

### CODE REVIEW

**Comment by cg505** [comment]
honestly we should treat these changes like staff hours, where as long as the tests pass you can merge w/o approval. otherwise it's gonna get real painful real fast

**Comment by jvperrin** [comment]
Agreed, this isn't meant to slow down the process, more to have some actual tests and version control around changes

**Comment by nikhiljha** [comment]
@cg505 this is the first time I'm doing this so I'm trying to be extra sure I don't mess anything up :P

**Comment by cg505** [comment]
for sure, it's worth considering in general though

**Pull request merged**
